"""
Refine proof code generated by LLM
"""

from loguru import logger
from pathlib import Path
import shutil
import hashlib
import re
import subprocess

from src import vars as global_vars
from src.analyzer.verus import VerusError
from src.analyzer.report import Reporter
from src.llm.prompter import (
    FixFVTPrompter,
    FixFVTSimplePrompter,
    VerusProvePrompter,
    VerusProveSimplePrompter,
)
from .refine_agents import VerusErrorRefiner
from .validate import Validator
from src.prover.collector import VerusInfoCollector
from src.prover.fvt import FVT, FVTStage
from src.prover.utils import VerifyStatus


class DriverRunAttempt:
    """
    Try to run a FVT.
    Used with "with" statement.
    Return the status and message of the run.
    """

    # Whether to cleanup the files after the run
    CLEANUP = False

    CMD = ""

    def __init__(self, fvt: FVT):
        self.fvt = fvt

    def __enter__(self):
        self.fvt.preprocess(self.fvt.out_path)
        result = self.fvt.run()
        logger.debug(
            f"Execution of fvt {self.fvt.id} result: {result[0]}, content:\n{result[1][-4000:]}"
        )
        return result

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.CLEANUP and hasattr(self, "dest_path"):
            # clean up
            shutil.rmtree(self.dest_path)


class Refiner:
    """
    Class to refine formal verification target (FVT) code
    """

    # config constants
    CONSOLIDATE_CHAT_HISTORY = True
    LEVEL = "function"
    REQUIRE_UNIFIED_DIFF = False

    def __init__(self):
        """
        Initialize the refiner
        """
        pass

    def fix(self, fvt: FVT, err_msg: str, prompter_class):
        """
        Fix proof code using LLM

        :param fvt: The formal verification target
        :param err_msg: The error message
        :param prompter_class: The Prompter class to use, FixFVTPrompter or ProveFVTPrompter
        """
        verus_errs = VerusError(err_msg, fvt)
        prompter = prompter_class(fvt.llm_chat)

        def _looks_like_unified_diff(text: str) -> bool:
            if not text:
                return False
            # Typical markers: diff --git, ---/+++ headers, and @@ hunks.
            return bool(
                re.search(r"^diff --git ", text, re.M)
                or (
                    re.search(r"^---\s+", text, re.M)
                    and re.search(r"^\+\+\+\s+", text, re.M)
                )
                # Allow leading whitespace because some models indent hunks.
                or re.search(r"^\s*@@\s+-\d+", text, re.M)
            )

        def _normalize_patch_for_file(patch_text: str, target_file: Path) -> str:
            repo_root = Path(global_vars.kverus_path)
            target_rel = str(target_file.resolve().relative_to(repo_root.resolve()))

            lines = patch_text.splitlines(keepends=True)

            # Some LLMs emit a non-standard header like:
            #   a/code.rs\n
            #   b/code.rs\n
            #   @@ -... +... @@
            # Convert it into a real unified diff header so `patch` can apply it.
            if (
                len(lines) >= 3
                and lines[0].strip() == "a/code.rs"
                and lines[1].strip() == "b/code.rs"
                and re.match(r"^\s*@@\s+-\d+", lines[2])
            ):
                lines = [f"--- {target_rel}\n", f"+++ {target_rel}\n"] + lines[2:]

            out_lines: list[str] = []
            for raw_line in lines:
                # The `patch` utility doesn't require the git header line.
                if raw_line.startswith("diff --git "):
                    continue

                # Rewrite placeholder headers to the actual relative path.
                if raw_line.startswith("--- "):
                    out_lines.append(f"--- {target_rel}\n")
                    continue
                if raw_line.startswith("+++ "):
                    out_lines.append(f"+++ {target_rel}\n")
                    continue

                # Also rewrite placeholder filenames if they appear elsewhere.
                raw_line = raw_line.replace("a/code.rs", target_rel).replace(
                    "b/code.rs", target_rel
                )
                out_lines.append(raw_line)

            return "".join(out_lines)

        def _apply_unified_diff_to_file(patch_text: str, target_file: Path) -> bool:
            repo_root = Path(global_vars.kverus_path)
            normalized = _normalize_patch_for_file(patch_text, target_file)

            # Apply with the system `patch` tool (available on Linux, no git repo required).
            proc = subprocess.run(
                ["patch", "-u", "-p0", "--forward", "--batch"],
                input=normalized.encode("utf-8"),
                cwd=str(repo_root),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            if proc.returncode != 0:
                logger.error(
                    "Failed to apply unified diff with `patch` (exit={}). stdout:\n{}\nstderr:\n{}".format(
                        proc.returncode,
                        proc.stdout.decode("utf-8", errors="replace"),
                        proc.stderr.decode("utf-8", errors="replace"),
                    )
                )
                return False
            return True

        def _write_back(path: Path, ori_code, err_msg, extra_knowledge: str = ""):
            if fvt.llm_chat is None:
                logger.error(f"Cannot refine FVT {fvt.id} without an LLM chat")
                return
            verus_err_refiner = VerusErrorRefiner(
                Path(global_vars.fvt_config["database_path"]) / "comprehender" / "docs"
            )
            if not FVT.DISABLE_VERUS:
                extra_knowledge += verus_err_refiner.refine_error(ori_code, err_msg)
            extra_knowledge += fvt.meta_knowledge or ""
            # verus_info_collector = VerusInfoCollector()
            # extra_knowledge += verus_info_collector.collect_meta_knowledge(
            #     fvt.info, fvt.main_func.location
            # )
            fixed_code = prompter.prompt(ori_code, err_msg, extra_knowledge)
            fvt.llm_chat.remove_last_query()
            fvt.query_count += 1
            if fixed_code == "":
                logger.error(f"No fixed code generated for FVT {path}")
                return
            else:
                validator = Validator()

                # If the model returns a unified diff, apply it to the file.
                if _looks_like_unified_diff(fixed_code):
                    logger.debug(f"LLM returned a diff for FVT {path}; applying patch")
                    if not _apply_unified_diff_to_file(fixed_code, path):
                        logger.error(f"Failed to apply diff for FVT {path}, skip")
                        return
                    # For bookkeeping, store the resulting full file contents.
                    fixed_code = path.read_text(encoding="utf-8")
                else:
                    if self.REQUIRE_UNIFIED_DIFF:
                        logger.error(
                            "LLM output is not a unified diff (diff-only mode enabled); skip. "
                            "Ensure prompts force ```diff ...``` output."
                        )
                        logger.debug(
                            f"Non-diff LLM output for FVT {path}:\n{fixed_code}"
                        )
                        return

                    if not validator.validate(fvt, ori_code, fixed_code):
                        logger.error(f"Fixed code is not valid for FVT {path}, skip")
                        return
                    logger.debug("Why no unified diff?")
                    logger.debug(f"Fixed code for FVT {path}:\n{fixed_code}")
                    fvt_file_code = path.read_text(encoding="utf-8")
                    fvt_file_code = fvt_file_code.replace(ori_code, fixed_code)
                    path.write_text(fvt_file_code, encoding="utf-8")

            updated_code = path.read_text(encoding="utf-8")
            fvt.record_stage_artifact(updated_code)

            if fvt.ori_code == None:
                fvt.ori_code = ori_code

        def _fix_file_level():
            logger.info("fix by file level")

            for verus_file_err in verus_errs.file_errors:
                fvt_file_code = verus_file_err.path.read_text(encoding="utf-8")
                # FIXME: Only RAG lemma for once, do we need to do it for every error?
                if prompter_class is VerusProvePrompter and fvt.has_rag_lemma == False:
                    fvt.has_rag_lemma = True
                    info_collector = VerusInfoCollector()
                    extra_knowledge = info_collector.collect_prove_knowledge(
                        fvt,
                        fvt_file_code,
                        verus_file_err.get_file_error_msg(),
                    )
                    logger.debug(f"Extra knowledge: {extra_knowledge}")
                else:
                    extra_knowledge = ""

                _write_back(
                    verus_file_err.path,
                    fvt_file_code,
                    verus_file_err.get_file_error_msg(),
                    extra_knowledge,
                )

        def _fix_func_level():
            logger.info("fix by func level")
            for verus_func_err in verus_errs.func_errors:
                if verus_func_err.func_impl != None:
                    fvt_func_code = verus_func_err.func_impl[0].get_content_till_pos(
                        verus_func_err.func_impl[1]
                    )
                    _write_back(
                        verus_func_err.path,
                        fvt_func_code,
                        verus_func_err.get_func_error_msg(),
                    )
                else:
                    for err in verus_func_err.errors:
                        start_pos = err.file_pos.copy()
                        start_pos.line -= 10
                        start_pos.set_to_start_of_line()
                        end_pos = err.file_pos.copy()
                        end_pos.line += 10
                        end_pos.set_to_end_of_line()
                        fvt_part_code = start_pos.get_content_till_pos(end_pos)
                        _write_back(
                            verus_func_err.path,
                            fvt_part_code,
                            verus_func_err.get_func_error_msg(),
                        )

        if self.LEVEL == "file":
            _fix_file_level()
        elif self.LEVEL == "function":
            _fix_func_level()
        else:
            logger.critical(f"Unknown fix level {self.LEVEL}, please check the config")
        if self.CONSOLIDATE_CHAT_HISTORY:
            self._consolidate_chat_history(fvt)

    def refine(self, fvt: FVT, status: VerifyStatus, err_msg: str):
        """
        Try to run refinement on the fvt once

        :param fvt: The fvt to be refined
        """
        # subtract the remaining refinement rounds
        fvt.remain_refine_rounds -= 1
        logger.info(
            f"Refining fvt {fvt.id}, remaining rounds: {fvt.remain_refine_rounds}"
        )

        match status:
            case VerifyStatus.SUCCESS:
                # Should never reach here
                logger.critical(f"FVT {fvt.id} already succeeded, no need to refine")
                exit(1)
            case VerifyStatus.VERIFY_ERROR:
                logger.info(f"Verify error detected in FVT {fvt.id}, fixing...")
                if fvt.DISABLE_VERUS:
                    self.fix(fvt, err_msg, VerusProveSimplePrompter)
                else:
                    self.fix(fvt, err_msg, VerusProvePrompter)
            case VerifyStatus.BUILD_ERROR:
                logger.info(f"Build error detected in FVT {fvt.id}, fixing...")
                if fvt.DISABLE_VERUS:
                    self.fix(fvt, err_msg, FixFVTSimplePrompter)
                else:
                    self.fix(fvt, err_msg, FixFVTPrompter)

    def refine_until_success(self, fvt: FVT, file_path=None):
        out_path = Path(global_vars.fvt_config["output_path"]) / "prover"

        if fvt.current_stage == FVTStage.PREPROCESS:
            fvt.set_stage(FVTStage.PROVE)

        resolved_file_path = Path(file_path) if file_path is not None else None

        # Precompute file hash if a file path is provided so it's available in all branches
        file_path_hash = (
            hashlib.md5(str(resolved_file_path).encode()).hexdigest()
            if resolved_file_path is not None
            else None
        )

        # Prepare a small helper to optionally backup current file
        backup_target = (
            (out_path / file_path_hash) if file_path_hash is not None else None
        )

        fvt.record_current_token()

        def _maybe_backup():
            if resolved_file_path is not None and backup_target is not None:
                fvt.backup(resolved_file_path, backup_target)

        while fvt.refined == False:
            status, err_msg = fvt.run()
            if status == VerifyStatus.SUCCESS:
                logger.info(f"FVT {fvt.id} succeeded")
                fvt.refined = True
                if resolved_file_path is not None and resolved_file_path.exists():
                    fvt.record_stage_artifact(
                        resolved_file_path.read_text(encoding="utf-8")
                    )
                # Also backup the file when verification succeeds
                _maybe_backup()
                break
            if fvt.remain_refine_rounds == 0:
                fvt.last_err_msg = err_msg
                logger.warning(f"FVT {fvt.id} reached max refinement rounds")
                break
            _maybe_backup()
            self.refine(fvt, status, err_msg)
            fvt.preprocess(fvt.out_path)

        if resolved_file_path is not None and file_path_hash is not None:
            log_path = out_path / f"{file_path_hash}.json"
            fvt.log_status(log_path)
        report_path = (
            out_path
            / f"{file_path_hash if resolved_file_path is not None else 'failure'}-report.md"
        )
        Reporter().generate_failure_report(fvt, report_path)

    @staticmethod
    def _consolidate_chat_history(fvt: FVT):
        """
        Consolidate chat history: system prompt - gen prompt - code response 1 - fix prompt - code response 2
        Into: system prompt - gen prompt - code response 2
        """
        if fvt.llm_chat is None:
            return
        if len(fvt.llm_chat.history) < 5:
            return
        old_history = fvt.llm_chat.history
        new_history = [
            old_history[0],
            old_history[-2],
            {
                "role": "assistant",
                "content": old_history[-1]["content"],
            },
        ]
        fvt.llm_chat.history = new_history
